# Generated by Django 4.1.1 on 2022-11-09 21:01

from django.db import migrations, models

import phone_book.models


class Migration(migrations.Migration):
    dependencies = [
        ("phone_book", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Contact",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("name", models.CharField(max_length=255)),
                ("phone", models.CharField(max_length=100)),
                ("birthday_date", models.DateField()),
                ("create_at", models.DateTimeField(auto_now_add=True)),
                ("modified_at", models.DateTimeField(auto_now=True)),
                ("is_auto_generated", models.BooleanField(default=False)),
                (
                    "avatar",
                    models.ImageField(
                        blank=True, max_length=255, null=True, upload_to=phone_book.models.get_avatar_path
                    ),
                ),
            ],
            options={
                "verbose_name": "Contact",
                "verbose_name_plural": "Phone Book",
                "ordering": ["-create_at"],
            },
        ),
        migrations.DeleteModel(
            name="PhoneBook",
        ),
    ]
