# Generated by Django 4.1.1 on 2022-10-20 17:52

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("phone_book", "0003_alter_phonebook_phone"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="PhoneBook",
            new_name="Contacts",
        ),
    ]
