# Generated by Django 4.1.1 on 2022-11-05 14:19

from django.db import migrations, models

import phone_book.models


class Migration(migrations.Migration):
    dependencies = [
        ("phone_book", "0008_contact_avatar"),
    ]

    operations = [
        migrations.AlterField(
            model_name="contact",
            name="avatar",
            field=models.ImageField(blank=True, max_length=255, null=True, upload_to=phone_book.models.get_avatar_path),
        ),
    ]
